<?php

$countries = [
    ['Afghanistan','AF','Asia'],
    ['Albania','AL','Europe'],
    ['Algeria','DZ','Africa'],
    ['American Samoa','AS','Oceania'],
    ['Andorra','AD','Europe'],
    ['Angola','AO','Africa'],
    ['Anguilla','AI','Americas'],
    ['Antigua and Barbuda','AG','Americas'],
    ['Argentina','AR','Americas'],
    ['Armenia','AM','Asia'],
    ['Aruba','AW','Americas'],
    ['Australia','AU','Oceania'],
    ['Austria','AT','Europe'],
    ['Azerbaijan','AZ','Asia'],
    ['Bahamas','BS','Americas'],
    ['Bahrain','BH','Asia'],
    ['Bangladesh','BD','Asia'],
    ['Barbados','BB','Americas'],
    ['Belarus','BY','Europe'],
    ['Belgium','BE','Europe'],
    ['Belize','BZ','Americas'],
    ['Benin','BJ','Africa'],
    ['Bermuda','BM','Americas'],
    ['Bhutan','BT','Asia'],
    ['Bolivia (Plurinational State of)','BO','Americas'],
    ['Bonaire, Sint Eustatius and Saba','BQ','Americas'],
    ['Bosnia and Herzegovina','BA','Europe'],
    ['Botswana','BW','Africa'],
    ['Bouvet Island','BV','Americas'],
    ['Brazil','BR','Americas'],
    ['British Indian Ocean Territory','IO','Africa'],
    ['British Virgin Islands','VG','Americas'],
    ['Brunei Darussalam','BN','Asia'],
    ['Bulgaria','BG','Europe'],
    ['Burkina Faso','BF','Africa'],
    ['Burundi','BI','Africa'],
    ['Cabo Verde','CV','Africa'],
    ['Cambodia','KH','Asia'],
    ['Cameroon','CM','Africa'],
    ['Canada','CA','Americas'],
    ['Cayman Islands','KY','Americas'],
    ['Central African Republic','CF','Africa'],
    ['Chad','TD','Africa'],
    ['Chile','CL','Americas'],
    ['China','CN','Asia'],
    ['China, Hong Kong Special Administrative Region','HK','Asia'],
    ['China, Macao Special Administrative Region','MO','Asia'],
    ['Christmas Island','CX','Oceania'],
    ['Cocos (Keeling) Islands','CC','Oceania'],
    ['Colombia','CO','Americas'],
    ['Comoros','KM','Africa'],
    ['Congo','CG','Africa'],
    ['Cook Islands','CK','Oceania'],
    ['Costa Rica','CR','Americas'],
    ['Croatia','HR','Europe'],
    ['Cuba','CU','Americas'],
    ['Curaçao','CW','Americas'],
    ['Cyprus','CY','Asia'],
    ['Czechia','CZ','Europe'],
    ['Côte d\'Ivoire','CI','Africa'],
    ['Democratic People\'s Republic of Korea','KP','Asia'],
    ['Democratic Republic of the Congo','CD','Africa'],
    ['Denmark','DK','Europe'],
    ['Djibouti','DJ','Africa'],
    ['Dominica','DM','Americas'],
    ['Dominican Republic','DO','Americas'],
    ['Ecuador','EC','Americas'],
    ['Egypt','EG','Africa'],
    ['El Salvador','SV','Americas'],
    ['Equatorial Guinea','GQ','Africa'],
    ['Eritrea','ER','Africa'],
    ['Estonia','EE','Europe'],
    ['Ethiopia','ET','Africa'],
    ['Falkland Islands (Malvinas)','FK','Americas'],
    ['Faroe Islands','FO','Europe'],
    ['Fiji','FJ','Oceania'],
    ['Finland','FI','Europe'],
    ['France','FR','Europe'],
    ['French Guiana','GF','Americas'],
    ['French Polynesia','PF','Oceania'],
    ['French Southern Territories','TF','Africa'],
    ['Gabon','GA','Africa'],
    ['Gambia','GM','Africa'],
    ['Georgia','GE','Asia'],
    ['Germany','DE','Europe'],
    ['Ghana','GH','Africa'],
    ['Gibraltar','GI','Europe'],
    ['Greece','GR','Europe'],
    ['Greenland','GL','Americas'],
    ['Grenada','GD','Americas'],
    ['Guadeloupe','GP','Americas'],
    ['Guam','GU','Oceania'],
    ['Guatemala','GT','Americas'],
    ['Guernsey','GG','Europe'],
    ['Guinea','GN','Africa'],
    ['Guinea-Bissau','GW','Africa'],
    ['Guyana','GY','Americas'],
    ['Haiti','HT','Americas'],
    ['Heard Island and McDonald Islands','HM','Oceania'],
    ['Holy See','VA','Europe'],
    ['Honduras','HN','Americas'],
    ['Hungary','HU','Europe'],
    ['Iceland','IS','Europe'],
    ['India','IN','Asia'],
    ['Indonesia','ID','Asia'],
    ['Iran (Islamic Republic of)','IR','Asia'],
    ['Iraq','IQ','Asia'],
    ['Ireland','IE','Europe'],
    ['Isle of Man','IM','Europe'],
    ['Israel','IL','Asia'],
    ['Italy','IT','Europe'],
    ['Jamaica','JM','Americas'],
    ['Japan','JP','Asia'],
    ['Jersey','JE','Europe'],
    ['Jordan','JO','Asia'],
    ['Kazakhstan','KZ','Asia'],
    ['Kenya','KE','Africa'],
    ['Kiribati','KI','Oceania'],
    ['Kuwait','KW','Asia'],
    ['Kyrgyzstan','KG','Asia'],
    ['Lao People\'s Democratic Republic','LA','Asia'],
    ['Latvia','LV','Europe'],
    ['Lebanon','LB','Asia'],
    ['Lesotho','LS','Africa'],
    ['Liberia','LR','Africa'],
    ['Libya','LY','Africa'],
    ['Liechtenstein','LI','Europe'],
    ['Lithuania','LT','Europe'],
    ['Luxembourg','LU','Europe'],
    ['Madagascar','MG','Africa'],
    ['Malawi','MW','Africa'],
    ['Malaysia','MY','Asia'],
    ['Maldives','MV','Asia'],
    ['Mali','ML','Africa'],
    ['Malta','MT','Europe'],
    ['Marshall Islands','MH','Oceania'],
    ['Martinique','MQ','Americas'],
    ['Mauritania','MR','Africa'],
    ['Mauritius','MU','Africa'],
    ['Mayotte','YT','Africa'],
    ['Mexico','MX','Americas'],
    ['Micronesia (Federated States of)','FM','Oceania'],
    ['Monaco','MC','Europe'],
    ['Mongolia','MN','Asia'],
    ['Montenegro','ME','Europe'],
    ['Montserrat','MS','Americas'],
    ['Morocco','MA','Africa'],
    ['Mozambique','MZ','Africa'],
    ['Myanmar','MM','Asia'],
    ['Namibia','NA','Africa'],
    ['Nauru','NR','Oceania'],
    ['Nepal','NP','Asia'],
    ['Netherlands','NL','Europe'],
    ['New Caledonia','NC','Oceania'],
    ['New Zealand','NZ','Oceania'],
    ['Nicaragua','NI','Americas'],
    ['Niger','NE','Africa'],
    ['Nigeria','NG','Africa'],
    ['Niue','NU','Oceania'],
    ['Norfolk Island','NF','Oceania'],
    ['Northern Mariana Islands','MP','Oceania'],
    ['Norway','NO','Europe'],
    ['Oman','OM','Asia'],
    ['Pakistan','PK','Asia'],
    ['Palau','PW','Oceania'],
    ['Panama','PA','Americas'],
    ['Papua New Guinea','PG','Oceania'],
    ['Paraguay','PY','Americas'],
    ['Peru','PE','Americas'],
    ['Philippines','PH','Asia'],
    ['Pitcairn','PN','Oceania'],
    ['Poland','PL','Europe'],
    ['Portugal','PT','Europe'],
    ['Puerto Rico','PR','Americas'],
    ['Qatar','QA','Asia'],
    ['Republic of Korea','KR','Asia'],
    ['Republic of Moldova','MD','Europe'],
    ['Romania','RO','Europe'],
    ['Russian Federation','RU','Europe'],
    ['Rwanda','RW','Africa'],
    ['Réunion','RE','Africa'],
    ['Saint Barthélemy','BL','Americas'],
    ['Saint Helena','SH','Africa'],
    ['Saint Kitts and Nevis','KN','Americas'],
    ['Saint Lucia','LC','Americas'],
    ['Saint Martin (French Part)','MF','Americas'],
    ['Saint Pierre and Miquelon','PM','Americas'],
    ['Saint Vincent and the Grenadines','VC','Americas'],
    ['Samoa','WS','Oceania'],
    ['San Marino','SM','Europe'],
    ['Sao Tome and Principe','ST','Africa'],
    ['Saudi Arabia','SA','Asia'],
    ['Senegal','SN','Africa'],
    ['Serbia','RS','Europe'],
    ['Seychelles','SC','Africa'],
    ['Sierra Leone','SL','Africa'],
    ['Singapore','SG','Asia'],
    ['Sint Maarten (Dutch part)','SX','Americas'],
    ['Slovakia','SK','Europe'],
    ['Slovenia','SI','Europe'],
    ['Solomon Islands','SB','Oceania'],
    ['Somalia','SO','Africa'],
    ['South Africa','ZA','Africa'],
    ['South Georgia and the South Sandwich Islands','GS','Americas'],
    ['South Sudan','SS','Africa'],
    ['Spain','ES','Europe'],
    ['Sri Lanka','LK','Asia'],
    ['State of Palestine','PS','Asia'],
    ['Sudan','SD','Africa'],
    ['Suriname','SR','Americas'],
    ['Svalbard and Jan Mayen Islands','SJ','Europe'],
    ['Swaziland','SZ','Africa'],
    ['Sweden','SE','Europe'],
    ['Switzerland','CH','Europe'],
    ['Syrian Arab Republic','SY','Asia'],
    ['Tajikistan','TJ','Asia'],
    ['Thailand','TH','Asia'],
    ['The former Yugoslav Republic of Macedonia','MK','Europe'],
    ['Timor-Leste','TL','Asia'],
    ['Togo','TG','Africa'],
    ['Tokelau','TK','Oceania'],
    ['Tonga','TO','Oceania'],
    ['Trinidad and Tobago','TT','Americas'],
    ['Tunisia','TN','Africa'],
    ['Turkey','TR','Asia'],
    ['Turkmenistan','TM','Asia'],
    ['Turks and Caicos Islands','TC','Americas'],
    ['Tuvalu','TV','Oceania'],
    ['Uganda','UG','Africa'],
    ['Ukraine','UA','Europe'],
    ['United Arab Emirates','AE','Asia'],
    ['United Kingdom of Great Britain and Northern Ireland','GB','Europe'],
    ['United Republic of Tanzania','TZ','Africa'],
    ['United States Minor Outlying Islands','UM','Oceania'],
    ['United States Virgin Islands','VI','Americas'],
    ['United States of America','US','Americas'],
    ['Uruguay','UY','Americas'],
    ['Uzbekistan','UZ','Asia'],
    ['Vanuatu','VU','Oceania'],
    ['Venezuela (Bolivarian Republic of)','VE','Americas'],
    ['Viet Nam','VN','Asia'],
    ['Wallis and Futuna Islands','WF','Oceania'],
    ['Western Sahara','EH','Africa'],
    ['Yemen','YE','Asia'],
    ['Zambia','ZM','Africa'],
    ['Zimbabwe','ZW','Africa'],
    ['Åland Islands','AX','Europe']
];

$result = [];

$filter = strtolower($_GET['q'] ?? '');
$grouped= $_GET['grouped'] ?? null;
$fbenu  = $_GET['benu'] ?? null;

foreach($countries as $country){
    $name = $country[0];
    $code = $country[1];
    $benu = $country[2];

    if($fbenu && $benu != $fbenu)
        continue;

    if($filter
        && !strstr(strtolower($name), $filter)
        && !strstr(strtolower($code), $filter)
        && !strstr(strtolower($benu), $filter))
            continue;
            
    if(!is_null($grouped)){
        if(!isset($result[$benu]))
            $result[$benu] = [];
        $result[$benu][$code] = $name;
    }else{
        $result[$code] = $name;
    }
}

$data = json_encode($result);
header('Content-Type: application/json');
header('Connection: close');
header('Content-Length: ' . strlen($data));
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');
echo $data;